### ISSUE TITLE
Middleman v4 Support

### ISSUE THREAD

**Issue by jaredpike** [jcypret/middleman-title#1]
Currently returns when running Middleman: 

`/Library/Ruby/Gems/2.0.0/gems/middleman-core-4.1.6/lib/middleman-core/extensions.rb:96:in 'load': Tried to activate old-style extension: title. They are no longer supported. (RuntimeError)`

**Comment by cmer** [comment]
I've made an attempt at fixing this here: https://github.com/cmer/middleman-title/tree/middleman_4_compatibility

However, I can't get Middleman to recognize the `page_title` helper. If anybody has an idea why that'd be great.

**Comment by cmer** [comment]
I figured out what my issue was.

I have submitted a pull request. Would it be possible to merge please?

**Comment by jcypret** [comment]
@cmer Nice work! I hadn't gotten around to updating any extensions for Middleman 4 but the new API looks really nice to work with. Thanks for contributing!

I'll push a new version of the gem this evening.
